//! `keel deck` — the obligation review deck, generated by the ENGINE and saved through its OWN API.
//!
//! WHY THIS MOVED INTO RUST (issue192, their words: "make the artifact locally in rust, test
//! thoroughly, then deploy"). The python-generated deck saved through the Claude artifact live-doc
//! mechanism — the one component of the whole stack that cannot run locally. Five versions shipped on
//! inference about that runtime; three were broken by my own syntax errors and two by contract
//! misreadings, and NONE was testable before deploy. The loop was: guess, publish, ask the human.
//!
//! THE ARCHITECTURE THAT BREAKS THE LOOP: the deck's save path is now `keel serve`'s existing POST
//! endpoints — the same ones the console has used all along — which are Rust, local, and exercised
//! end-to-end by an httpx test before anything is published. The page detects its transport at load:
//! same-origin `/api/version` answers → LOCAL mode (tested); otherwise → INBOX mode: each tap is
//! delivered as a row to the sheet named in `.engine/contracts/deck-inbox.toml` through the viewer's
//! Smartsheet connector (Claude artifact `mcp` capability), and the STORE'S row id is the receipt the
//! page shows — real receiver-side acknowledgment. The AI session pulls unprocessed rows, records
//! them through the keel write API, verifies the computed view, and checks Processed.
//!
//! WHY THE LIVE-DOC MECHANISM IS GONE (issue194): its appends silently dropped — `sync()` resolved,
//! the page said saved, and neither keel nor the viewer's own reload ever saw the write. A transport
//! with no receiver-side acknowledgment cannot carry a save label (D0018 applied to a button).
//!
//! Save routing per class, all through EXISTING write paths:
//!   - finding    → POST /api/disposition   (Accept→act, Reject→dismiss; "Needs work" carries a note)
//!   - acceptance → POST /api/decision/accept | /api/decision/reject (the human signs)
//!   - sitting    → POST /api/deck/sitting  → `write::append_critique` as the HUMAN reviewer
//!
//! The sitting reviewer is embedded at generation time as the sole registered `Person`; a sitting
//! review is the per-sitting human gate (D0049) and may never be recorded as an AI.

use crate::json::Json;
use std::fmt::Write as _;
use std::path::Path;

/// A card on the deck.
struct Item {
    cls: &'static str,
    name: String,
    uid: String,
    title: String,
    meta: String,
    /// Repo-relative path of the file declaring the item — `/api/decision/accept|reject` require it.
    file: String,
}

/// The sole registered human reviewer, read from the actors registry.
///
/// Embedded into the page so a sitting review is recorded as THEM: the deck is the human's oversight
/// lens on their own machine, and the tap is theirs. If no Person is registered the sitting save path
/// is disabled rather than guessed.
fn sole_human(root: &Path) -> Option<String> {
    let text = std::fs::read_to_string(root.join(".tracking").join("actors.sysml")).ok()?;
    let mut found = None;
    for raw in text.lines() {
        let line = raw.trim_start();
        if line.starts_with("//") {
            continue;
        }
        if let Some(rest) = line.strip_prefix("part ") {
            if let Some((name, after)) = rest.split_once(':') {
                if after.trim_start().starts_with("Person") {
                    if found.is_some() {
                        return None; // two humans: do not guess which one is reviewing
                    }
                    found = Some(name.trim().to_string());
                }
            }
        }
    }
    found
}

/// The remote-inbox config from `.engine/contracts/deck-inbox.toml`, emitted as a JS object literal.
///
/// The MOBILE transport (issue194): when the page cannot reach keel serve it delivers each tap as a
/// row to this sheet through the viewer's Smartsheet connector. Every field is REQUIRED — a partial
/// config yields `null`, and the page then claims no transport rather than half of one.
fn inbox_js(root: &Path) -> String {
    let path = root.join(".engine").join("contracts").join("deck-inbox.toml");
    let Ok(text) = std::fs::read_to_string(path) else { return "null".to_string() };
    let Ok(v) = text.parse::<toml::Value>() else { return "null".to_string() };
    let Some(sheet) = v.get("sheet_id").and_then(toml::Value::as_integer) else { return "null".to_string() };
    let Some(cols) = v.get("columns").and_then(toml::Value::as_table) else { return "null".to_string() };
    let mut c = String::new();
    for key in ["uid", "name", "kind", "verdict", "note", "by", "at", "deck_head"] {
        let Some(id) = cols.get(key).and_then(toml::Value::as_integer) else { return "null".to_string() };
        let _ = write!(c, "{}{}:{id}", if c.is_empty() { "" } else { "," }, key.replace('_', ""));
    }
    format!("{{sheet:{sheet},cols:{{{c}}}}}")
}

/// `name -> (id, title, repo-relative file)` for every declared item — the same scan guard 37 walks.
fn item_index(root: &Path) -> std::collections::BTreeMap<String, (String, String, String)> {
    let mut out = std::collections::BTreeMap::new();
    for base in [".tracking", ".engine"] {
        for f in crate::collect_sysml(&root.join(base)) {
            let rel = f
                .strip_prefix(root)
                .map_or_else(|_| f.to_string_lossy().to_string(), |p| p.to_string_lossy().to_string())
                .replace('\\', "/");
            let Ok(text) = std::fs::read_to_string(&f) else { continue };
            let mut lines = text.lines().peekable();
            while let Some(raw) = lines.next() {
                let line = raw.trim_start();
                if line.starts_with("//") {
                    continue;
                }
                let after_marker = line.strip_prefix('#').map_or(line, |r| {
                    r.split_once(char::is_whitespace).map_or("", |(_, rest)| rest.trim_start())
                });
                let Some(rest) = after_marker.strip_prefix("part ") else { continue };
                let Some((name, _)) = rest.split_once(':') else { continue };
                let name = name.trim().to_string();
                if out.contains_key(&name) {
                    continue;
                }
                // id/title usually sit within the next few lines
                let mut id = String::new();
                let mut title = String::new();
                let mut scan = String::from(line);
                for _ in 0..6 {
                    if let Some(peek) = lines.peek() {
                        scan.push('\n');
                        scan.push_str(peek);
                        lines.next();
                    }
                }
                for cap in scan.split(":>>") {
                    let c = cap.trim_start();
                    if let Some(v) = c.strip_prefix("id = \"") {
                        id = v.split('"').next().unwrap_or("").to_string();
                    }
                    if let Some(v) = c.strip_prefix("title = \"") {
                        title = v.split('"').next().unwrap_or("").to_string();
                    }
                }
                if !id.is_empty() {
                    out.insert(name, (id, title, rel.clone()));
                }
            }
        }
    }
    out
}

/// Collect the obligation set from the SAME computed views the console reads (never enumerated).
fn collect(root: &Path) -> Vec<Item> {
    let idx = item_index(root);
    let mut items: Vec<Item> = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    let mut add = |cls: &'static str, name: &str, meta: String| {
        let Some((uid, title, file)) = idx.get(name) else { return };
        if !seen.insert(uid.clone()) {
            return;
        }
        let shown = title
            .split_once(": ")
            .filter(|(h, _)| h.eq_ignore_ascii_case(name))
            .map_or_else(|| title.clone(), |(_, t)| t.to_string());
        items.push(Item {
            cls,
            name: name.to_string(),
            uid: uid.clone(),
            title: if shown.is_empty() { name.to_string() } else { shown },
            meta,
            file: file.clone(),
        });
    };
    let parse = |s: String| serde_json::from_str::<serde_json::Value>(&s).unwrap_or(serde_json::Value::Null);
    let orient = parse(crate::orient::compute(root).to_json());
    let empty = Vec::new();
    for d in orient.get("pendingAcceptances").and_then(|v| v.as_array()).unwrap_or(&empty) {
        if let Some(n) = d.as_str() {
            add("acceptance", n, "proposed - needs your signature".to_string());
        }
    }
    let disp = parse(crate::view::dispositions(root).unwrap_or_default());
    for f in disp.get("findings").and_then(|v| v.as_array()).unwrap_or(&empty) {
        if !f.get("dispositioned").and_then(serde_json::Value::as_bool).unwrap_or(true) {
            if let Some(n) = f.get("finding").and_then(|v| v.as_str()) {
                let sev = f.get("severity").and_then(|v| v.as_str()).unwrap_or("?");
                add("finding", n, format!("severity {sev}"));
            }
        }
    }
    let sit = parse(crate::view::sitting_coverage(root).unwrap_or_default());
    for s in sit.get("due_sprints").and_then(|v| v.as_array()).unwrap_or(&empty) {
        if let Some(n) = s.as_str() {
            add("sitting", n, "unreviewed".to_string());
        }
    }
    items
}

/// The page. One self-contained HTML fragment (the artifact runtime supplies the head; a browser is
/// lenient about the same shape, so ONE output serves both transports).
///
/// # Errors
/// Returns [`crate::view::ViewError`] if the model cannot be read.
pub fn html(root: &Path) -> Result<String, crate::view::ViewError> {
    let items = collect(root);
    let human = sole_human(root).unwrap_or_default();
    let head_sha = crate::gitx::git()
        .arg("-C")
        .arg(root)
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map_or_else(|| "?".to_string(), |o| String::from_utf8_lossy(&o.stdout).trim().to_string());
    let esc = |s: &str| -> String {
        s.chars()
            .map(|c| match c {
                '&' => "&amp;".to_string(),
                '<' => "&lt;".to_string(),
                '>' => "&gt;".to_string(),
                '"' => "&quot;".to_string(),
                c if (c as u32) > 126 => format!("&#{};", c as u32),
                c => c.to_string(),
            })
            .collect()
    };
    let classes: [(&str, &str, &str); 3] = [
        ("acceptance", "Decisions awaiting your signature", "#4c5fd7"),
        ("finding", "Findings awaiting disposition", "#b5651d"),
        ("sitting", "Sitting reviews due", "#7d4f9c"),
    ];
    let mut sections = String::new();
    for (cls, label, hue) in classes {
        let rows: Vec<&Item> = items.iter().filter(|i| i.cls == cls).collect();
        let mut cards = String::new();
        for i in &rows {
            let verb = if cls == "acceptance" { "Sign" } else { "Accept" };
            let _ = write!(
                cards,
                "<article class=card data-id=\"{u}\" data-name=\"{n}\" data-cls=\"{c}\" data-file=\"{f}\" data-verdict=\"\">\
                 <header><code>{n}</code><span class=vd></span><span class=sv></span></header>\
                 <h3>{t}</h3><p class=meta>{m}</p>\
                 <div class=verdicts><button data-v=accept>{verb}</button>\
                 <button data-v=maybe>Needs work</button><button data-v=reject>Reject</button></div>\
                 <input class=note type=text data-id=\"{u}-note\" placeholder=\"why, or what to change\" aria-label=\"note\">\
                 </article>",
                u = esc(&i.uid),
                n = esc(&i.name),
                c = cls,
                f = esc(&i.file),
                t = esc(&i.title),
                m = esc(&i.meta),
            );
        }
        if cards.is_empty() {
            cards = "<p class=empty>Nothing outstanding in this class.</p>".to_string();
        }
        let _ = write!(
            sections,
            "<section class=grp data-local-open=\"{open}\" style=\"--h:{hue}\">\
             <button class=grph aria-expanded=\"{open}\"><span class=n>{n}</span><span class=t>{label}</span>\
             <span class=caret></span></button><div class=grpb>{cards}</div></section>",
            open = !rows.is_empty(),
            n = rows.len(),
        );
    }
    Ok(format!(
        "<title>Keel Obligations Deck</title>\n<meta name=viewport content=\"width=device-width,initial-scale=1\">\n\
         <style>{css}</style>\n<div class=wrap><header class=top><h1>Keel Obligations Deck</h1>\n\
         <p class=sub>{count} item(s) waiting on you &middot; HEAD {sha} &middot; deck v6-rust</p>\n\
         <p class=how id=how data-local-mode=\"detecting\">Tap a verdict; it records straight into keel.</p>\n\
         <artifact-local><div id=dbglog></div></artifact-local></header>\n{sections}</div>\n\
         <script>\nvar HUMAN={human};\nvar HEAD={head};\nvar INBOX={inbox};\n{js}</script>\n",
        css = CSS,
        count = items.len(),
        sha = esc(&head_sha),
        sections = sections,
        human = Json::s(human).dump(),
        head = Json::s(head_sha.clone()).dump(),
        inbox = inbox_js(root),
        js = JS,
    ))
}

const CSS: &str = r#"
:root{--ink:#0e1a1f;--ink2:#3c4f57;--ink3:#6d8189;--paper:#f3f6f6;--card:#fff;--line:#d5dfe0;
--accept:#2e7d4f;--maybe:#a67c00;--reject:#b5342b;--r:12px;
--sans:ui-sans-serif,system-ui,"Segoe UI",Roboto,sans-serif;--mono:ui-monospace,Consolas,monospace}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--ink:#e8f0f1;--ink2:#a6bcc2;
--ink3:#7b959d;--paper:#0b1418;--card:#121f24;--line:#25373d;--accept:#5fbf85;--maybe:#d9ad3c;--reject:#e8736a}}
:root[data-theme="dark"]{--ink:#e8f0f1;--ink2:#a6bcc2;--ink3:#7b959d;--paper:#0b1418;--card:#121f24;
--line:#25373d;--accept:#5fbf85;--maybe:#d9ad3c;--reject:#e8736a}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.5 var(--sans)}
.wrap{max-width:680px;margin:0 auto;padding:0 14px 40px}
h1{margin:18px 0 0;font-size:25px;font-weight:800}
.sub{margin:6px 0 0;color:var(--ink3);font:12px/1.5 var(--mono)}
.sub::after{content:' - script did NOT finish';color:var(--reject);font-weight:700}
body[data-local-js=ok] .sub::after{content:' - script ok';color:var(--accept)}
.how{margin:12px 0;color:var(--ink2);font-size:14px}
.how::after{content:attr(data-local-transport);color:var(--ink3);font:11px var(--mono);display:block}
#dbglog{font:10px/1.6 var(--mono);color:var(--ink3);max-height:8em;overflow-y:auto;
border:1px dashed var(--line);border-radius:8px;padding:5px 8px;margin:8px 0}
#dbglog:empty{display:none}
.grp{margin:16px 0 0;border:1px solid var(--line);border-radius:var(--r);background:var(--card);overflow:hidden}
.grph{width:100%;min-height:50px;display:flex;align-items:center;gap:10px;padding:12px;background:none;
border:0;border-left:4px solid var(--h);color:var(--ink);font:650 15px var(--sans);text-align:left;cursor:pointer}
.grph .n{font:700 15px var(--mono);color:var(--h)}
.grph .t{flex:1}
.caret{width:9px;height:9px;border-right:2px solid var(--ink3);border-bottom:2px solid var(--ink3);transform:rotate(45deg)}
.grp[data-local-open=true] .caret{transform:rotate(-135deg)}
.grpb{display:none;padding:0 12px 12px}
.grp[data-local-open=true] .grpb{display:block}
.card{border:1px solid var(--line);border-left:4px solid var(--h);border-radius:var(--r);padding:12px;margin:10px 0;background:var(--card)}
.card[data-verdict=accept]{border-color:var(--accept)}
.card[data-verdict=maybe]{border-color:var(--maybe)}
.card[data-verdict=reject]{border-color:var(--reject)}
.card header{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.card code{font:600 12px var(--mono);color:var(--ink3)}
.vd{display:none;font:700 10px var(--sans);text-transform:uppercase;padding:4px 8px;border-radius:99px;color:#fff}
.card[data-verdict=accept] .vd{display:inline-block;background:var(--accept)}
.card[data-verdict=accept] .vd::after{content:'accepted'}
.card[data-verdict=maybe] .vd{display:inline-block;background:var(--maybe);color:#1a1200}
.card[data-verdict=maybe] .vd::after{content:'needs work'}
.card[data-verdict=reject] .vd{display:inline-block;background:var(--reject)}
.card[data-verdict=reject] .vd::after{content:'rejected'}
.sv{font:11px var(--mono);color:var(--ink3)}
.sv::after{content:attr(data-local-sv)}
.card h3{margin:7px 0 0;font-size:15px;font-weight:650;line-height:1.35}
.meta{margin:6px 0 0;font:11px var(--mono);color:var(--ink3)}
.verdicts{display:flex;gap:6px;margin:11px 0 0}
.verdicts button{flex:1;min-height:44px;border:1px solid var(--line);border-radius:9px;background:transparent;
color:var(--ink2);font:600 13px var(--sans);cursor:pointer}
.card[data-verdict=accept] button[data-v=accept]{background:var(--accept);border-color:var(--accept);color:#fff}
.card[data-verdict=maybe] button[data-v=maybe]{background:var(--maybe);border-color:var(--maybe);color:#1a1200}
.card[data-verdict=reject] button[data-v=reject]{background:var(--reject);border-color:var(--reject);color:#fff}
.note{width:100%;min-height:44px;margin:8px 0 0;padding:10px;border:1px solid var(--line);border-radius:9px;
background:transparent;color:var(--ink);font:14px var(--sans)}
.card[data-cls=acceptance]{border-left-width:5px}
"#;

/// The page script. TINY by design, ASCII only, newline via fromCharCode, node-checked in tests.
const JS: &str = r"
var MODE = 'none';
var MCP = null, SERVER = 'Smartsheet';
function dbg(m){var el=document.getElementById('dbglog');if(!el)return;
  var d=document.createElement('div');d.textContent=m;el.insertBefore(d,el.firstChild);
  while(el.children.length>8){el.removeChild(el.lastChild);}}
window.onerror=function(m,s,l){dbg('ERROR '+m+' @'+l);return false;};
function setHow(m){document.getElementById('how').setAttribute('data-local-transport',m);}

// TRANSPORT DETECTION. Same-origin /api/version answering with apiVersion means keel serve is on the
// other side: the TESTED path. Anything else (the claude.ai artifact frame included, where this fetch
// fails) tries the INBOX: taps are delivered as rows to the keel-deck-inbox sheet through the
// viewer's Smartsheet connector, and the store's row id is the receipt. No connector -> say so.
fetch('/api/version').then(function(r){return r.json();}).then(function(j){
  if(j && j.apiVersion){MODE='local';setHow('transport: keel serve (tested path)');}
  else{initInbox();}
}).catch(function(){initInbox();});

function initInbox(){
  if(!INBOX||!(window.claude&&claude.use)){setHow('transport: NONE - nothing tapped here reaches keel; tell Claude your verdicts');return;}
  claude.use('mcp').then(function(m){
    if(!m){setHow('transport: NONE - this view cannot reach the inbox; tell Claude your verdicts');return;}
    MCP=m;MODE='inbox';
    setHow('transport: claude inbox - each tap is delivered to your keel-deck-inbox sheet with a receipt; Claude records it into keel');
    m.listTools().then(function(lt){
      var i,j,s;
      for(i=0;i<lt.servers.length;i++){s=lt.servers[i];
        for(j=0;j<s.tools.length;j++){if(s.tools[j].name==='add_rows'){SERVER=s.server;dbg('inbox via '+SERVER);return;}}}
      dbg('no connector offers add_rows');
    }).catch(function(e){dbg('listTools: '+((e&&e.code)||e));});
  }).catch(function(e){setHow('transport: NONE - tell Claude your verdicts');dbg('use(mcp): '+e);});
}

function say(card,msg){var sv=card.querySelector('.sv');if(sv)sv.setAttribute('data-local-sv',msg);}

function saveLocal(card,verdict){
  var cls=card.getAttribute('data-cls'), name=card.getAttribute('data-name');
  var noteEl=card.querySelector('.note'), note=noteEl?noteEl.value.trim():'';
  var today=new Date().toISOString().slice(0,10);
  var url='', body=null;
  if(cls==='finding'){
    if(verdict==='maybe'){say(card,'noted - needs-work carries no disposition; the note travels with your next verdict');return;}
    if(!HUMAN){say(card,'no registered human reviewer - a disposition may not be recorded without its judge');return;}
    url='/api/disposition';
    body={finding:name,verdict:(verdict==='accept'?'act':'dismiss'),rationale:(note||'tapped on the deck by '+HUMAN+' with no per-item note'),judged_at:today,judged_by:HUMAN};
  } else if(cls==='acceptance'){
    if(verdict==='maybe'){say(card,'noted - tell Claude what to change via the note, then Sign or Reject');return;}
    if(!HUMAN){say(card,'no registered human reviewer - cannot sign from the deck');return;}
    url=(verdict==='accept')?'/api/decision/accept':'/api/decision/reject';
    body={decision:name,file:card.getAttribute('data-file'),judged_at:today,judged_by:HUMAN};
    if(verdict==='accept'){body.note=(note||'signed via deck');}else{body.rationale=(note||'rejected via deck');}
  } else {
    if(!HUMAN){say(card,'no registered human reviewer - a sitting review may not be recorded as an AI');return;}
    url='/api/deck/sitting';
    body={story:name,verdict:verdict,note:note,by:HUMAN,judged_at:today};
  }
  say(card,'saving to keel...');
  fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
    .then(function(r){return r.json().then(function(j){return {ok:r.ok,j:j};});})
    .then(function(res){
      if(res.ok){say(card,'saved to keel');}
      else{say(card,'NOT saved: '+(res.j&&res.j.error||'error'));dbg('POST '+url+' failed: '+JSON.stringify(res.j));}
    })
    .catch(function(e){say(card,'NOT saved - is keel serve up?');dbg('POST '+url+' threw: '+e);});
}

// THE INBOX SAVE. The label ladder (D0018 on a button): the STORE'S row id earns 'delivered to
// inbox'; only keel's own API earns 'saved to keel'; ambiguous outcomes say UNKNOWN and invite a
// re-tap - a duplicate row is harmless because Claude dedups by uid, latest wins. Write errors are
// branched per contract code; never collapsed into one banner.
function saveInbox(card,verdict){
  if(!MCP){say(card,'NOT delivered - no transport; tell Claude this verdict');return;}
  var cls=card.getAttribute('data-cls'), name=card.getAttribute('data-name'), uid=card.getAttribute('data-id');
  var noteEl=card.querySelector('.note'), note=noteEl?noteEl.value.trim():'';
  var C=INBOX.cols;
  var row={toBottom:true,cells:[
    {columnId:C.uid,value:uid},{columnId:C.name,value:name},{columnId:C.kind,value:cls},
    {columnId:C.verdict,value:verdict},{columnId:C.note,value:note},
    {columnId:C.by,value:HUMAN||'unknown'},{columnId:C.at,value:new Date().toISOString()},
    {columnId:C.deckhead,value:HEAD}]};
  say(card,'delivering...');
  MCP.callTool(SERVER,'add_rows',{sheet_id:INBOX.sheet,rows:[row]}).then(function(r){
    var p=r&&r.payload, got=p&&p.result&&p.result[0]&&p.result[0].id;
    if(got){say(card,'delivered to inbox row '+(p.result[0].rowNumber||'?')+' - Claude records it into keel');}
    else{say(card,'delivered, receipt unreadable - ask Claude to check the inbox');dbg('ack: '+JSON.stringify(p).slice(0,140));}
  },function(err){
    var c=(err&&err.code)||'unknown';
    if(c==='needs_reauth'){say(card,'NOT delivered - reconnect Smartsheet in claude.ai Settings, Connectors, then tap again');}
    else if(c==='server_not_connected'){say(card,'NOT delivered - add Smartsheet in claude.ai Settings, Connectors, then tap again');}
    else if(c==='selection_required'){say(card,'NOT delivered - choose a Smartsheet connector when prompted, then tap again');}
    else if(c==='tool_error'){say(card,'inbox REFUSED: '+String((err&&err.message)||'').slice(0,90));}
    else if(c==='server_unavailable'||c==='upstream_error'||c==='cancelled'){say(card,'delivery UNKNOWN - tap again to retry; a duplicate row is harmless');}
    else{say(card,'NOT delivered ('+c+')');}
    dbg('add_rows '+c+': '+((err&&err.message)||''));
  });
}

document.addEventListener('click',function(e){
  var h=e.target.closest('.grph');
  if(h){var g=h.closest('.grp');var open=g.getAttribute('data-local-open')!=='true';
    g.setAttribute('data-local-open',open?'true':'false');
    h.setAttribute('aria-expanded',open?'true':'false');return;}
  var b=e.target.closest('.verdicts button');
  if(!b)return;
  var card=b.closest('.card');
  var next=card.getAttribute('data-verdict')===b.getAttribute('data-v')?'':b.getAttribute('data-v');
  card.setAttribute('data-verdict',next);
  if(!next){say(card,'cleared (nothing recorded)');return;}
  if(MODE==='local'){saveLocal(card,next);}else{saveInbox(card,next);}
});

// LAST STATEMENT: `script ok` in the header means every listener above registered.
document.body.setAttribute('data-local-js','ok');
";

#[cfg(test)]
mod tests {
    use super::*;

    /// PASS ZERO (issue191, now enforced at the source): the emitted script must PARSE. Checked with
    /// node when available; a missing node SKIPS LOUDLY rather than passing vacuously (issue183's
    /// false-green rule).
    #[test]
    fn the_emitted_script_parses() {
        let dir = std::env::temp_dir().join("keel-deck-jscheck");
        let _ = std::fs::create_dir_all(&dir);
        let js_path = dir.join("deck.js");
        std::fs::write(&js_path, format!("var HUMAN=\"t\";\nvar HEAD=\"x\";\nvar INBOX=null;\n{JS}"))
            .expect("write js");
        match std::process::Command::new("node").arg("--check").arg(&js_path).output() {
            Ok(out) => {
                assert!(
                    out.status.success(),
                    "emitted JS does not parse:\n{}",
                    String::from_utf8_lossy(&out.stderr)
                );
            }
            Err(_) => {
                // Absence of node must be VISIBLE in the test output, never a silent pass.
                eprintln!("SKIPPED: node not on PATH - the emitted-JS parse check did not run");
            }
        }
    }

    /// The script must write NO text into the synced region: attribute writes only, plus the exempt
    /// debug panel. Pinned at the source so the python generator's fate cannot repeat.
    #[test]
    fn no_synced_text_writes_in_the_script() {
        for line in JS.lines() {
            let s = line.trim_start();
            if s.starts_with("//") || s.contains("d.textContent") {
                continue; // the dbg panel's own node lives in <artifact-local>, exempt by contract
            }
            assert!(
                !s.contains("textContent =") && !s.contains("innerHTML"),
                "synced text write in the deck script: {s}"
            );
        }
    }

    /// The last statement is the liveness marker — its absence on screen means the script threw.
    #[test]
    fn the_liveness_marker_is_last() {
        assert!(JS.trim_end().ends_with("document.body.setAttribute('data-local-js','ok');"));
    }

    /// The live-doc mechanism is RETIRED (issue194: its appends silently dropped). Nothing in the
    /// script may reach for it again; the mobile fallback is the inbox, whose ack is the store's.
    #[test]
    fn the_dead_live_doc_mechanism_stays_dead() {
        assert!(!JS.contains(".sync("), "live-doc sync() reappeared in the deck script");
        assert!(!JS.contains("use('artifact')"), "the artifact capability reappeared in the deck script");
        assert!(JS.contains("callTool"), "the inbox transport is missing from the deck script");
    }

    /// The inbox config round-trips from the contract file, and a missing or PARTIAL file yields
    /// `null` — the page must claim no transport rather than half of one.
    #[test]
    fn inbox_config_all_or_nothing() {
        let dir = std::env::temp_dir().join("keel-deck-inbox-cfg");
        let contracts = dir.join(".engine").join("contracts");
        let _ = std::fs::create_dir_all(&contracts);
        let _ = std::fs::remove_file(contracts.join("deck-inbox.toml"));
        assert_eq!(inbox_js(&dir), "null", "absent file must yield null");
        let full = "sheet_id = 42\n[columns]\nuid = 1\nname = 2\nkind = 3\nverdict = 4\nnote = 5\nby = 6\nat = 7\ndeck_head = 8\n";
        std::fs::write(contracts.join("deck-inbox.toml"), full).expect("write cfg");
        assert_eq!(
            inbox_js(&dir),
            "{sheet:42,cols:{uid:1,name:2,kind:3,verdict:4,note:5,by:6,at:7,deckhead:8}}"
        );
        let partial = "sheet_id = 42\n[columns]\nuid = 1\n";
        std::fs::write(contracts.join("deck-inbox.toml"), partial).expect("write cfg");
        assert_eq!(inbox_js(&dir), "null", "partial config must yield null");
    }
}
