//! `keel deck` — the obligation review deck, generated by the ENGINE and saved through its OWN API.
//!
//! WHY THIS MOVED INTO RUST (issue192, their words: "make the artifact locally in rust, test
//! thoroughly, then deploy"). The python-generated deck saved through the Claude artifact live-doc
//! mechanism — the one component of the whole stack that cannot run locally. Five versions shipped on
//! inference about that runtime; three were broken by my own syntax errors and two by contract
//! misreadings, and NONE was testable before deploy. The loop was: guess, publish, ask the human.
//!
//! THE ARCHITECTURE THAT BREAKS THE LOOP: the deck's save path is now `keel serve`'s existing POST
//! endpoints — the same ones the console has used all along — which are Rust, local, and exercised
//! end-to-end by an httpx test before anything is published. The artifact live-doc mechanism is
//! DEMOTED TO FALLBACK for the phone, where the page cannot reach a local server. The page detects its
//! transport at load: same-origin `/api/version` answers → LOCAL mode (tested); otherwise → artifact
//! mode (the contract-compliant v5 mechanism).
//!
//! Save routing per class, all through EXISTING write paths:
//!   - finding    → POST /api/disposition   (Accept→act, Reject→dismiss; "Needs work" carries a note)
//!   - acceptance → POST /api/decision/accept | /api/decision/reject (the human signs)
//!   - sitting    → POST /api/deck/sitting  → `write::append_critique` as the HUMAN reviewer
//!
//! The sitting reviewer is embedded at generation time as the sole registered `Person`; a sitting
//! review is the per-sitting human gate (D0049) and may never be recorded as an AI.

use crate::json::Json;
use std::fmt::Write as _;
use std::path::Path;

/// A card on the deck.
struct Item {
    cls: &'static str,
    name: String,
    uid: String,
    title: String,
    meta: String,
}

/// The sole registered human reviewer, read from the actors registry.
///
/// Embedded into the page so a sitting review is recorded as THEM: the deck is the human's oversight
/// lens on their own machine, and the tap is theirs. If no Person is registered the sitting save path
/// is disabled rather than guessed.
fn sole_human(root: &Path) -> Option<String> {
    let text = std::fs::read_to_string(root.join(".tracking").join("actors.sysml")).ok()?;
    let mut found = None;
    for raw in text.lines() {
        let line = raw.trim_start();
        if line.starts_with("//") {
            continue;
        }
        if let Some(rest) = line.strip_prefix("part ") {
            if let Some((name, after)) = rest.split_once(':') {
                if after.trim_start().starts_with("Person") {
                    if found.is_some() {
                        return None; // two humans: do not guess which one is reviewing
                    }
                    found = Some(name.trim().to_string());
                }
            }
        }
    }
    found
}

/// `name -> (id, title)` for every declared item — the same scan guard 37 walks.
fn item_index(root: &Path) -> std::collections::BTreeMap<String, (String, String)> {
    let mut out = std::collections::BTreeMap::new();
    for base in [".tracking", ".engine"] {
        for f in crate::collect_sysml(&root.join(base)) {
            let Ok(text) = std::fs::read_to_string(&f) else { continue };
            let mut lines = text.lines().peekable();
            while let Some(raw) = lines.next() {
                let line = raw.trim_start();
                if line.starts_with("//") {
                    continue;
                }
                let after_marker = line.strip_prefix('#').map_or(line, |r| {
                    r.split_once(char::is_whitespace).map_or("", |(_, rest)| rest.trim_start())
                });
                let Some(rest) = after_marker.strip_prefix("part ") else { continue };
                let Some((name, _)) = rest.split_once(':') else { continue };
                let name = name.trim().to_string();
                if out.contains_key(&name) {
                    continue;
                }
                // id/title usually sit within the next few lines
                let mut id = String::new();
                let mut title = String::new();
                let mut scan = String::from(line);
                for _ in 0..6 {
                    if let Some(peek) = lines.peek() {
                        scan.push('\n');
                        scan.push_str(peek);
                        lines.next();
                    }
                }
                for cap in scan.split(":>>") {
                    let c = cap.trim_start();
                    if let Some(v) = c.strip_prefix("id = \"") {
                        id = v.split('"').next().unwrap_or("").to_string();
                    }
                    if let Some(v) = c.strip_prefix("title = \"") {
                        title = v.split('"').next().unwrap_or("").to_string();
                    }
                }
                if !id.is_empty() {
                    out.insert(name, (id, title));
                }
            }
        }
    }
    out
}

/// Collect the obligation set from the SAME computed views the console reads (never enumerated).
fn collect(root: &Path) -> Vec<Item> {
    let idx = item_index(root);
    let mut items: Vec<Item> = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    let mut add = |cls: &'static str, name: &str, meta: String| {
        let Some((uid, title)) = idx.get(name) else { return };
        if !seen.insert(uid.clone()) {
            return;
        }
        let shown = title
            .split_once(": ")
            .filter(|(h, _)| h.eq_ignore_ascii_case(name))
            .map_or_else(|| title.clone(), |(_, t)| t.to_string());
        items.push(Item {
            cls,
            name: name.to_string(),
            uid: uid.clone(),
            title: if shown.is_empty() { name.to_string() } else { shown },
            meta,
        });
    };
    let parse = |s: String| serde_json::from_str::<serde_json::Value>(&s).unwrap_or(serde_json::Value::Null);
    let orient = parse(crate::orient::compute(root).to_json());
    let empty = Vec::new();
    for d in orient.get("pendingAcceptances").and_then(|v| v.as_array()).unwrap_or(&empty) {
        if let Some(n) = d.as_str() {
            add("acceptance", n, "proposed - needs your signature".to_string());
        }
    }
    let disp = parse(crate::view::dispositions(root).unwrap_or_default());
    for f in disp.get("findings").and_then(|v| v.as_array()).unwrap_or(&empty) {
        if !f.get("dispositioned").and_then(serde_json::Value::as_bool).unwrap_or(true) {
            if let Some(n) = f.get("finding").and_then(|v| v.as_str()) {
                let sev = f.get("severity").and_then(|v| v.as_str()).unwrap_or("?");
                add("finding", n, format!("severity {sev}"));
            }
        }
    }
    let sit = parse(crate::view::sitting_coverage(root).unwrap_or_default());
    for s in sit.get("due_sprints").and_then(|v| v.as_array()).unwrap_or(&empty) {
        if let Some(n) = s.as_str() {
            add("sitting", n, "unreviewed".to_string());
        }
    }
    items
}

/// The page. One self-contained HTML fragment (the artifact runtime supplies the head; a browser is
/// lenient about the same shape, so ONE output serves both transports).
///
/// # Errors
/// Returns [`crate::view::ViewError`] if the model cannot be read.
pub fn html(root: &Path) -> Result<String, crate::view::ViewError> {
    let items = collect(root);
    let human = sole_human(root).unwrap_or_default();
    let head_sha = crate::gitx::git()
        .arg("-C")
        .arg(root)
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map_or_else(|| "?".to_string(), |o| String::from_utf8_lossy(&o.stdout).trim().to_string());
    let esc = |s: &str| -> String {
        s.chars()
            .map(|c| match c {
                '&' => "&amp;".to_string(),
                '<' => "&lt;".to_string(),
                '>' => "&gt;".to_string(),
                '"' => "&quot;".to_string(),
                c if (c as u32) > 126 => format!("&#{};", c as u32),
                c => c.to_string(),
            })
            .collect()
    };
    let classes: [(&str, &str, &str); 3] = [
        ("acceptance", "Decisions awaiting your signature", "#4c5fd7"),
        ("finding", "Findings awaiting disposition", "#b5651d"),
        ("sitting", "Sitting reviews due", "#7d4f9c"),
    ];
    let mut sections = String::new();
    for (cls, label, hue) in classes {
        let rows: Vec<&Item> = items.iter().filter(|i| i.cls == cls).collect();
        let mut cards = String::new();
        for i in &rows {
            let verb = if cls == "acceptance" { "Sign" } else { "Accept" };
            let _ = write!(
                cards,
                "<article class=card data-id=\"{u}\" data-name=\"{n}\" data-cls=\"{c}\" data-verdict=\"\">\
                 <header><code>{n}</code><span class=vd></span><span class=sv></span></header>\
                 <h3>{t}</h3><p class=meta>{m}</p>\
                 <div class=verdicts><button data-v=accept>{verb}</button>\
                 <button data-v=maybe>Needs work</button><button data-v=reject>Reject</button></div>\
                 <input class=note type=text data-id=\"{u}-note\" placeholder=\"why, or what to change\" aria-label=\"note\">\
                 </article>",
                u = esc(&i.uid),
                n = esc(&i.name),
                c = cls,
                t = esc(&i.title),
                m = esc(&i.meta),
            );
        }
        if cards.is_empty() {
            cards = "<p class=empty>Nothing outstanding in this class.</p>".to_string();
        }
        let _ = write!(
            sections,
            "<section class=grp data-local-open=\"{open}\" style=\"--h:{hue}\">\
             <button class=grph aria-expanded=\"{open}\"><span class=n>{n}</span><span class=t>{label}</span>\
             <span class=caret></span></button><div class=grpb>{cards}</div></section>",
            open = !rows.is_empty(),
            n = rows.len(),
        );
    }
    Ok(format!(
        "<title>Keel Obligations Deck</title>\n<meta name=viewport content=\"width=device-width,initial-scale=1\">\n\
         <style>{css}</style>\n<div class=wrap><header class=top><h1>Keel Obligations Deck</h1>\n\
         <p class=sub>{count} item(s) waiting on you &middot; HEAD {sha} &middot; deck v6-rust</p>\n\
         <p class=how id=how data-local-mode=\"detecting\">Tap a verdict; it records straight into keel.</p>\n\
         <artifact-local><div id=dbglog></div></artifact-local></header>\n{sections}</div>\n\
         <script>\nvar HUMAN={human};\n{js}</script>\n",
        css = CSS,
        count = items.len(),
        sha = esc(&head_sha),
        sections = sections,
        human = Json::s(human).dump(),
        js = JS,
    ))
}

const CSS: &str = r#"
:root{--ink:#0e1a1f;--ink2:#3c4f57;--ink3:#6d8189;--paper:#f3f6f6;--card:#fff;--line:#d5dfe0;
--accept:#2e7d4f;--maybe:#a67c00;--reject:#b5342b;--r:12px;
--sans:ui-sans-serif,system-ui,"Segoe UI",Roboto,sans-serif;--mono:ui-monospace,Consolas,monospace}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--ink:#e8f0f1;--ink2:#a6bcc2;
--ink3:#7b959d;--paper:#0b1418;--card:#121f24;--line:#25373d;--accept:#5fbf85;--maybe:#d9ad3c;--reject:#e8736a}}
:root[data-theme="dark"]{--ink:#e8f0f1;--ink2:#a6bcc2;--ink3:#7b959d;--paper:#0b1418;--card:#121f24;
--line:#25373d;--accept:#5fbf85;--maybe:#d9ad3c;--reject:#e8736a}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.5 var(--sans)}
.wrap{max-width:680px;margin:0 auto;padding:0 14px 40px}
h1{margin:18px 0 0;font-size:25px;font-weight:800}
.sub{margin:6px 0 0;color:var(--ink3);font:12px/1.5 var(--mono)}
.sub::after{content:' - script did NOT finish';color:var(--reject);font-weight:700}
body[data-local-js=ok] .sub::after{content:' - script ok';color:var(--accept)}
.how{margin:12px 0;color:var(--ink2);font-size:14px}
.how::after{content:attr(data-local-transport);color:var(--ink3);font:11px var(--mono);display:block}
#dbglog{font:10px/1.6 var(--mono);color:var(--ink3);max-height:8em;overflow-y:auto;
border:1px dashed var(--line);border-radius:8px;padding:5px 8px;margin:8px 0}
#dbglog:empty{display:none}
.grp{margin:16px 0 0;border:1px solid var(--line);border-radius:var(--r);background:var(--card);overflow:hidden}
.grph{width:100%;min-height:50px;display:flex;align-items:center;gap:10px;padding:12px;background:none;
border:0;border-left:4px solid var(--h);color:var(--ink);font:650 15px var(--sans);text-align:left;cursor:pointer}
.grph .n{font:700 15px var(--mono);color:var(--h)}
.grph .t{flex:1}
.caret{width:9px;height:9px;border-right:2px solid var(--ink3);border-bottom:2px solid var(--ink3);transform:rotate(45deg)}
.grp[data-local-open=true] .caret{transform:rotate(-135deg)}
.grpb{display:none;padding:0 12px 12px}
.grp[data-local-open=true] .grpb{display:block}
.card{border:1px solid var(--line);border-left:4px solid var(--h);border-radius:var(--r);padding:12px;margin:10px 0;background:var(--card)}
.card[data-verdict=accept]{border-color:var(--accept)}
.card[data-verdict=maybe]{border-color:var(--maybe)}
.card[data-verdict=reject]{border-color:var(--reject)}
.card header{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.card code{font:600 12px var(--mono);color:var(--ink3)}
.vd{display:none;font:700 10px var(--sans);text-transform:uppercase;padding:4px 8px;border-radius:99px;color:#fff}
.card[data-verdict=accept] .vd{display:inline-block;background:var(--accept)}
.card[data-verdict=accept] .vd::after{content:'accepted'}
.card[data-verdict=maybe] .vd{display:inline-block;background:var(--maybe);color:#1a1200}
.card[data-verdict=maybe] .vd::after{content:'needs work'}
.card[data-verdict=reject] .vd{display:inline-block;background:var(--reject)}
.card[data-verdict=reject] .vd::after{content:'rejected'}
.sv{font:11px var(--mono);color:var(--ink3)}
.sv::after{content:attr(data-local-sv)}
.card h3{margin:7px 0 0;font-size:15px;font-weight:650;line-height:1.35}
.meta{margin:6px 0 0;font:11px var(--mono);color:var(--ink3)}
.verdicts{display:flex;gap:6px;margin:11px 0 0}
.verdicts button{flex:1;min-height:44px;border:1px solid var(--line);border-radius:9px;background:transparent;
color:var(--ink2);font:600 13px var(--sans);cursor:pointer}
.card[data-verdict=accept] button[data-v=accept]{background:var(--accept);border-color:var(--accept);color:#fff}
.card[data-verdict=maybe] button[data-v=maybe]{background:var(--maybe);border-color:var(--maybe);color:#1a1200}
.card[data-verdict=reject] button[data-v=reject]{background:var(--reject);border-color:var(--reject);color:#fff}
.note{width:100%;min-height:44px;margin:8px 0 0;padding:10px;border:1px solid var(--line);border-radius:9px;
background:transparent;color:var(--ink);font:14px var(--sans)}
.card[data-cls=acceptance]{border-left-width:5px}
"#;

/// The page script. TINY by design, ASCII only, newline via fromCharCode, node-checked in tests.
const JS: &str = r"
var MODE = 'artifact';
function dbg(m){var el=document.getElementById('dbglog');if(!el)return;
  var d=document.createElement('div');d.textContent=m;el.insertBefore(d,el.firstChild);
  while(el.children.length>8){el.removeChild(el.lastChild);}}
window.onerror=function(m,s,l){dbg('ERROR '+m+' @'+l);return false;};

// TRANSPORT DETECTION. Same-origin /api/version answering with apiVersion means keel serve is on the
// other side: the TESTED path. Anything else (the claude.ai artifact frame included, where this fetch
// 404s) falls back to the artifact live-doc mechanism.
fetch('/api/version').then(function(r){return r.json();}).then(function(j){
  if(j && j.apiVersion){MODE='local';
    document.getElementById('how').setAttribute('data-local-transport','transport: keel serve (tested path)');}
}).catch(function(){
  document.getElementById('how').setAttribute('data-local-transport','transport: artifact live-doc (fallback)');
});

var ART = (window.claude && claude.use) ? claude.use('artifact') : Promise.resolve(null);

function say(card,msg){var sv=card.querySelector('.sv');if(sv)sv.setAttribute('data-local-sv',msg);}

function saveLocal(card,verdict){
  var cls=card.getAttribute('data-cls'), name=card.getAttribute('data-name');
  var noteEl=card.querySelector('.note'), note=noteEl?noteEl.value.trim():'';
  var today=new Date().toISOString().slice(0,10);
  var url='', body=null;
  if(cls==='finding'){
    if(verdict==='maybe'){say(card,'noted - needs-work carries no disposition; the note travels with your next verdict');return;}
    url='/api/disposition';
    body={finding:name,verdict:(verdict==='accept'?'act':'dismiss'),rationale:(note||'via deck'),judged_at:today};
  } else if(cls==='acceptance'){
    if(verdict==='maybe'){say(card,'noted - tell Claude what to change via the note, then Sign or Reject');return;}
    if(!HUMAN){say(card,'no registered human reviewer - cannot sign from the deck');return;}
    url=(verdict==='accept')?'/api/decision/accept':'/api/decision/reject';
    body={decision:name,judged_at:today,judged_by:HUMAN,note:(note||'signed via deck')};
  } else {
    if(!HUMAN){say(card,'no registered human reviewer - a sitting review may not be recorded as an AI');return;}
    url='/api/deck/sitting';
    body={story:name,verdict:verdict,note:note,by:HUMAN,judged_at:today};
  }
  say(card,'saving to keel...');
  fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
    .then(function(r){return r.json().then(function(j){return {ok:r.ok,j:j};});})
    .then(function(res){
      if(res.ok){say(card,'saved to keel');}
      else{say(card,'NOT saved: '+(res.j&&res.j.error||'error'));dbg('POST '+url+' failed: '+JSON.stringify(res.j));}
    })
    .catch(function(e){say(card,'NOT saved - is keel serve up?');dbg('POST '+url+' threw: '+e);});
}

function saveArtifact(card,verdict){
  say(card,'saving...');
  ART.then(function(a){
    if(!a||!a.sync){say(card,'not saved - this view cannot write');return;}
    return a.sync(function(){ if(card.getAttribute('data-verdict')!==verdict){card.setAttribute('data-verdict',verdict);} })
      .then(function(){say(card,'saved');},
            function(err){say(card,'NOT saved ('+((err&&err.code)||'unknown')+')');dbg('sync rejected: '+((err&&err.code)||'?'));});
  }).catch(function(e){say(card,'not saved');dbg('sync threw: '+e);});
}

document.addEventListener('click',function(e){
  var h=e.target.closest('.grph');
  if(h){var g=h.closest('.grp');var open=g.getAttribute('data-local-open')!=='true';
    g.setAttribute('data-local-open',open?'true':'false');
    h.setAttribute('aria-expanded',open?'true':'false');return;}
  var b=e.target.closest('.verdicts button');
  if(!b)return;
  var card=b.closest('.card');
  var next=card.getAttribute('data-verdict')===b.getAttribute('data-v')?'':b.getAttribute('data-v');
  card.setAttribute('data-verdict',next);
  if(!next){say(card,'cleared (nothing recorded)');return;}
  if(MODE==='local'){saveLocal(card,next);}else{saveArtifact(card,next);}
});

// LAST STATEMENT: `script ok` in the header means every listener above registered.
document.body.setAttribute('data-local-js','ok');
";

#[cfg(test)]
mod tests {
    use super::*;

    /// PASS ZERO (issue191, now enforced at the source): the emitted script must PARSE. Checked with
    /// node when available; a missing node SKIPS LOUDLY rather than passing vacuously (issue183's
    /// false-green rule).
    #[test]
    fn the_emitted_script_parses() {
        let dir = std::env::temp_dir().join("keel-deck-jscheck");
        let _ = std::fs::create_dir_all(&dir);
        let js_path = dir.join("deck.js");
        std::fs::write(&js_path, format!("var HUMAN=\"t\";\n{JS}")).expect("write js");
        match std::process::Command::new("node").arg("--check").arg(&js_path).output() {
            Ok(out) => {
                assert!(
                    out.status.success(),
                    "emitted JS does not parse:\n{}",
                    String::from_utf8_lossy(&out.stderr)
                );
            }
            Err(_) => {
                // Absence of node must be VISIBLE in the test output, never a silent pass.
                eprintln!("SKIPPED: node not on PATH - the emitted-JS parse check did not run");
            }
        }
    }

    /// The script must write NO text into the synced region: attribute writes only, plus the exempt
    /// debug panel. Pinned at the source so the python generator's fate cannot repeat.
    #[test]
    fn no_synced_text_writes_in_the_script() {
        for line in JS.lines() {
            let s = line.trim_start();
            if s.starts_with("//") || s.contains("d.textContent") {
                continue; // the dbg panel's own node lives in <artifact-local>, exempt by contract
            }
            assert!(
                !s.contains("textContent =") && !s.contains("innerHTML"),
                "synced text write in the deck script: {s}"
            );
        }
    }

    /// The last statement is the liveness marker — its absence on screen means the script threw.
    #[test]
    fn the_liveness_marker_is_last() {
        assert!(JS.trim_end().ends_with("document.body.setAttribute('data-local-js','ok');"));
    }
}
